[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"  # or "build" or "out" depending on your framework output

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"